"""Application constants."""

# Sentiment values
SENTIMENT_POSITIVE = "positive"
SENTIMENT_NEGATIVE = "negative"
SENTIMENT_NEUTRAL = "neutral"
VALID_SENTIMENTS = {SENTIMENT_POSITIVE, SENTIMENT_NEGATIVE, SENTIMENT_NEUTRAL}

# Feedback sources
SOURCE_SUPPORT_TICKET = "support_ticket"
SOURCE_SURVEY = "survey"
SOURCE_APP_STORE = "app_store"
VALID_SOURCES = {SOURCE_SUPPORT_TICKET, SOURCE_SURVEY, SOURCE_APP_STORE}

# Pagination defaults
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# AI limits
MAX_FEEDBACK_FOR_SUMMARY = 50
MAX_FEEDBACK_FOR_BATCH = 100

# Date formats
ISO_DATE_FORMAT = "%Y-%m-%dT%H:%M:%S%z"

